In [1]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Activation
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.


In [2]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

In [3]:
# load dataset
dataset = numpy.genfromtxt("datasets/thermostat/sample-training-data.csv", delimiter=",")
X = dataset[:,0:11].astype(float)
Y = dataset[:,11]

In [4]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [5]:
print(encoded_Y)
print(dummy_y)

[2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 0 0 0 0 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 1 2 2 2 2 2 2]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.

In [6]:
input_dimension = X.shape[1]
print(input_dimension)
# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(11, activation='relu', input_dim=input_dimension))
    model.add(Dense(units=3))
    model.add(Activation("softmax"))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

11


In [7]:
model = baseline_model()

In [8]:
model.fit(X,dummy_y, epochs=100, batch_size=3)

Epoch 1/100
72/72 [==============================] - 1s 7ms/step - loss: 12.4100 - acc: 0.0417 
Epoch 2/100
72/72 [==============================] - 0s 694us/step - loss: 3.8190 - acc: 0.1944
Epoch 3/100
72/72 [==============================] - 0s 750us/step - loss: 0.6930 - acc: 0.7639
Epoch 4/100
72/72 [==============================] - 0s 667us/step - loss: 0.6094 - acc: 0.7917
Epoch 5/100
72/72 [==============================] - 0s 708us/step - loss: 0.5454 - acc: 0.8194
Epoch 6/100
72/72 [==============================] - 0s 694us/step - loss: 0.5284 - acc: 0.7917
Epoch 7/100
72/72 [==============================] - 0s 667us/step - loss: 0.5109 - acc: 0.8056
Epoch 8/100
72/72 [==============================] - 0s 778us/step - loss: 0.4926 - acc: 0.7917
Epoch 9/100
72/72 [==============================] - 0s 542us/step - loss: 0.4904 - acc: 0.8056
Epoch 10/100
72/72 [==============================] - 0s 708us/step - loss: 0.4823 - acc: 0.8056
Epoch 11/100
72/72 [===================

In [33]:
def getTestInput():
    month=12
    day=12
    hour=0
    minute=0
    pirstatus=0
    isDay=0
    extTemp=5
    extHumidity=55
    loungeTemp=16
    loungeHumidity=35
    state=0
    
    return numpy.array([month,day,hour,minute,pirstatus,isDay,extTemp,extHumidity,loungeTemp,loungeHumidity,state]).reshape((1,11))


In [1]:
#input = numpy.array(X[17]).reshape((1,11))
input  = getTestInput()
print(input)
result = model.predict(input)
for res in result:
    print(res)
result = model.predict_classes(input)
for res in result:
    print(res)

NameError: name 'getTestInput' is not defined